#!/bin/bash

echo "🚀 Deployment Checklist for Chatsuu"
echo "===================================="
echo ""
echo "Before deploying, complete these steps:"
echo ""
echo "BACKEND SETUP:"
echo "[ ] 1. Create MongoDB Atlas account & cluster"
echo "[ ] 2. Get MongoDB connection string"
echo "[ ] 3. Create Cloudinary account"
echo "[ ] 4. Get Cloudinary credentials"
echo "[ ] 5. Create backend/.env with all variables"
echo ""
echo "VERSION CONTROL:"
echo "[ ] 6. Commit all changes: git add . && git commit -m 'Setup deployment'"
echo "[ ] 7. Push to GitHub: git push"
echo ""
echo "RENDER DEPLOYMENT:"
echo "[ ] 8. Go to render.com"
echo "[ ] 9. Create Web Service for backend"
echo "[ ] 10. Set environment variables on Render"
echo "[ ] 11. Deploy backend (note the URL)"
echo "[ ] 12. Create Static Site for frontend"
echo "[ ] 13. Set VITE_API_URL env var with backend URL"
echo "[ ] 14. Deploy frontend"
echo ""
echo "TESTING:"
echo "[ ] 15. Test backend API"
echo "[ ] 16. Test frontend loads"
echo "[ ] 17. Test login/signup"
echo "[ ] 18. Test real-time chat"
echo ""
echo "✅ All done! Your app is live!"
