services:
  - type: web
    name: chatsuu-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        scope: all
      - key: JWT_SECRET
        scope: all
      - key: CLOUDINARY_CLOUD_NAME
        scope: all
      - key: CLOUDINARY_API_KEY
        scope: all
      - key: CLOUDINARY_API_SECRET
        scope: all
